(cl:in-package #:constrictor-test)

(defun test-acons ()
  (rt:do-test 'cl-test::acons.1)
  (rt:do-test 'cl-test::acons.2)
  (rt:do-test 'cl-test::acons.3)
  (rt:do-test 'cl-test::acons.4)
  (rt:do-test 'cl-test::acons.5)
  (rt:do-test 'cl-test::acons.6)
  (rt:do-test 'cl-test::acons.7)
  (rt:do-test 'cl-test::acons.8)
  (rt:do-test 'cl-test::acons.9)
  (rt:do-test 'cl-test::acons.order.1)
  (rt:do-test 'cl-test::acons.error.1)
  (rt:do-test 'cl-test::acons.error.2)
  (rt:do-test 'cl-test::acons.error.3)
  (rt:do-test 'cl-test::acons.error.4))
