(cl:in-package #:constrictor-test)

;;; We comment out tests that assume that NIL is a valid element of an
;;; association list.

(defun test-assoc ()
  (rt:do-test 'cl-test::assoc.1)
;;   (rt:do-test 'cl-test::assoc.2)
;;  (rt:do-test 'cl-test::assoc.3)
  (rt:do-test 'cl-test::assoc.4)
  (rt:do-test 'cl-test::assoc.5)
  (rt:do-test 'cl-test::assoc.6)
  (rt:do-test 'cl-test::assoc.7)
  (rt:do-test 'cl-test::assoc.8)
  (rt:do-test 'cl-test::assoc.9)
  (rt:do-test 'cl-test::assoc.10)
  (rt:do-test 'cl-test::assoc.11)
  (rt:do-test 'cl-test::assoc.12)
  (rt:do-test 'cl-test::assoc.13)
  (rt:do-test 'cl-test::assoc.14)
  (rt:do-test 'cl-test::assoc.15)
  (rt:do-test 'cl-test::assoc.16)
  (rt:do-test 'cl-test::assoc.17)
  (rt:do-test 'cl-test::assoc.18)
  (rt:do-test 'cl-test::assoc.19)
  (rt:do-test 'cl-test::assoc.20)
  (rt:do-test 'cl-test::assoc.21)
  (rt:do-test 'cl-test::assoc.22)
  (rt:do-test 'cl-test::assoc.23)
  (rt:do-test 'cl-test::assoc.24)
  (rt:do-test 'cl-test::assoc.25)
  (rt:do-test 'cl-test::assoc.26)
  (rt:do-test 'cl-test::assoc.27)
;;  (rt:do-test 'cl-test::assoc.30)
;;  (rt:do-test 'cl-test::assoc.31)
  (rt:do-test 'cl-test::assoc.order.1)
  (rt:do-test 'cl-test::assoc.order.2)
  (rt:do-test 'cl-test::assoc.order.3)
  (rt:do-test 'cl-test::assoc.order.4)
  (rt:do-test 'cl-test::assoc.allow-other-keys.1)
  (rt:do-test 'cl-test::assoc.allow-other-keys.2)
  (rt:do-test 'cl-test::assoc.allow-other-keys.3)
  (rt:do-test 'cl-test::assoc.allow-other-keys.4)
  (rt:do-test 'cl-test::assoc.allow-other-keys.5)
  (rt:do-test 'cl-test::assoc.keywords.6)
  (rt:do-test 'cl-test::assoc.keywords.7)
  (rt:do-test 'cl-test::assoc.error.1)
  (rt:do-test 'cl-test::assoc.error.2)
  (rt:do-test 'cl-test::assoc.error.3)
  (rt:do-test 'cl-test::assoc.error.4)
  (rt:do-test 'cl-test::assoc.error.5)
  (rt:do-test 'cl-test::assoc.error.6)
  (rt:do-test 'cl-test::assoc.error.7)
  (rt:do-test 'cl-test::assoc.error.8)
  (rt:do-test 'cl-test::assoc.error.9)
;;  (rt:do-test 'cl-test::assoc.error.10)
  (rt:do-test 'cl-test::assoc.error.11)
  (rt:do-test 'cl-test::assoc.error.12))

