(cl:in-package #:constrictor-test)

(defun test-butlast ()
  (rt:do-test 'cl-test::butlast.1)
  (rt:do-test 'cl-test::butlast.2)
  (rt:do-test 'cl-test::butlast.3)
  (rt:do-test 'cl-test::butlast.4)
  (rt:do-test 'cl-test::butlast.5)
  (rt:do-test 'cl-test::butlast.6)
  (rt:do-test 'cl-test::butlast.7)
  (rt:do-test 'cl-test::butlast.8)
  (rt:do-test 'cl-test::butlast.9)
  (rt:do-test 'cl-test::butlast.order.1)
  (rt:do-test 'cl-test::butlast.order.2)
  (rt:do-test 'cl-test::butlast.error.1)
  (rt:do-test 'cl-test::butlast.error.2)
  (rt:do-test 'cl-test::butlast.error.3)
  (rt:do-test 'cl-test::butlast.error.4)
  (rt:do-test 'cl-test::butlast.error.5))
