(cl:in-package #:asdf-user)

(defsystem #:constrictor-test
  :depends-on (#:constrictor-extrinsic
               #:ansi-test-common)
  :serial t
  :components
  ((:file "packages")
   (:file "prepare")
   (:file "endp")
   (:file "subst")
   (:file "subst-if")
   (:file "subst-if-not")
   (:file "list-length")
   (:file "assoc")
   (:file "assoc-if")
   (:file "assoc-if-not")
   (:file "rassoc")
   (:file "rassoc-if")
   (:file "rassoc-if-not")
   (:file "last")
   (:file "ldiff")
   (:file "tailp")
   (:file "member")
   (:file "member-if")
   (:file "member-if-not")
   (:file "mapcar")
   (:file "mapc")
   (:file "mapl")
   (:file "mapcan")
   (:file "maplist")
   (:file "mapcon")
   (:file "acons")
   (:file "nthcdr")
   (:file "append")
   (:file "test")))
