(cl:in-package #:constrictor-test)

(defun test-get-properties ()
  (rt:do-test 'cl-test::get-properties.1)
  (rt:do-test 'cl-test::get-properties.2)
  (rt:do-test 'cl-test::get-properties.3)
  (rt:do-test 'cl-test::get-properties.4)
  (rt:do-test 'cl-test::get-properties.5)
  (rt:do-test 'cl-test::get-properties.6)
  (rt:do-test 'cl-test::get-properties.7)
  ;; (rt:do-test 'cl-test::get-properties.8)
  (rt:do-test 'cl-test::get-properties.9)
  (rt:do-test 'cl-test::get-properties.order.1)
  (rt:do-test 'cl-test::get-properties.error.1)
  (rt:do-test 'cl-test::get-properties.error.2)
  (rt:do-test 'cl-test::get-properties.error.3)
  (rt:do-test 'cl-test::get-properties.error.4)
  (rt:do-test 'cl-test::get-properties.error.5)
  (rt:do-test 'cl-test::get-properties.error.6))
