(cl:in-package #:constrictor-test)

(defun test-getf ()
  (rt:do-test 'cl-test::getf.1)
  (rt:do-test 'cl-test::getf.2)
  (rt:do-test 'cl-test::getf.3)
  (rt:do-test 'cl-test::getf.4)
  (rt:do-test 'cl-test::getf.5)
  (rt:do-test 'cl-test::getf.order.1)
  (rt:do-test 'cl-test::getf.order.2)
  (rt:do-test 'cl-test::setf-getf.1)
  (rt:do-test 'cl-test::setf-getf.2)
  (rt:do-test 'cl-test::setf-getf.3)
  (rt:do-test 'cl-test::setf-getf.4)
  (rt:do-test 'cl-test::setf-getf.5)
  (rt:do-test 'cl-test::setf-getf.order.1)
  (rt:do-test 'cl-test::setf-getf.order.2)
  (rt:do-test 'cl-test::incf-getf.1)
  (rt:do-test 'cl-test::incf-getf.2)
  (rt:do-test 'cl-test::push-getf.1)
  (rt:do-test 'cl-test::getf.error.1)
  (rt:do-test 'cl-test::getf.error.2)
  (rt:do-test 'cl-test::getf.error.3)
  (rt:do-test 'cl-test::getf.error.4)
  (rt:do-test 'cl-test::getf.error.5))
