(cl:in-package #:constrictor-test)

(defun test-ldiff ()
  (rt:do-test 'cl-test::ldiff.1)
  (rt:do-test 'cl-test::ldiff.2)
  (rt:do-test 'cl-test::ldiff.3)
  (rt:do-test 'cl-test::ldiff.4)
  (rt:do-test 'cl-test::ldiff.5)
  (rt:do-test 'cl-test::ldiff.6)
  (rt:do-test 'cl-test::ldiff.7)
  (rt:do-test 'cl-test::ldiff.8)
  (rt:do-test 'cl-test::ldiff.order.1)
  (rt:do-test 'cl-test::ldiff.error.1)
  (rt:do-test 'cl-test::ldiff.error.2)
  (rt:do-test 'cl-test::ldiff.error.3)
  (rt:do-test 'cl-test::ldiff.error.4)
  (rt:do-test 'cl-test::ldiff.error.5)
  (rt:do-test 'cl-test::ldiff.error.6)
  (rt:do-test 'cl-test::ldiff.error.7)
  (rt:do-test 'cl-test::ldiff.error.8))
