(cl:in-package #:constrictor-test)

(defun test-make-list ()
  (rt:do-test 'cl-test::make-list-empty.1)
  (rt:do-test 'cl-test::make-list-empty.2)
  (rt:do-test 'cl-test::make-list-no-initial-element)
  (rt:do-test 'cl-test::make-list-with-initial-element)
  (rt:do-test 'cl-test::make-list.allow-other-keys.1)
  (rt:do-test 'cl-test::make-list.allow-other-keys.2)
  (rt:do-test 'cl-test::make-list.allow-other-keys.3)
  (rt:do-test 'cl-test::make-list.allow-other-keys.4)
  (rt:do-test 'cl-test::make-list.allow-other-keys.5)
  (rt:do-test 'cl-test::make-list-repeated-keyword)
  (rt:do-test 'cl-test::make-list.order.1)
  (rt:do-test 'cl-test::make-list.order.2)
  (rt:do-test 'cl-test::make-list.error.1)
  (rt:do-test 'cl-test::make-list.error.3)
  (rt:do-test 'cl-test::make-list.error.4)
  (rt:do-test 'cl-test::make-list.error.5)
  (rt:do-test 'cl-test::make-list.error.6)
  (rt:do-test 'cl-test::make-list.error.7)
  (rt:do-test 'cl-test::make-list.error.8))
