(cl:in-package #:constrictor-test)

(defun test-mapcan ()
  (rt:do-test 'cl-test::mapcan.1)
  (rt:do-test 'cl-test::mapcan.2)
  (rt:do-test 'cl-test::mapcan.3)
  (rt:do-test 'cl-test::mapcan.4)
  (rt:do-test 'cl-test::mapcan.5)
  (rt:do-test 'cl-test::mapcan.6)
  (rt:do-test 'cl-test::mapcan.order.1)
  (rt:do-test 'cl-test::mapcan.8)
  (rt:do-test 'cl-test::mapcan.9)
  (rt:do-test 'cl-test::mapcan.10)
  (rt:do-test 'cl-test::mapcan.11)
  (rt:do-test 'cl-test::mapcan.error.1)
  (rt:do-test 'cl-test::mapcan.error.2)
  (rt:do-test 'cl-test::mapcan.error.3)
  (rt:do-test 'cl-test::mapcan.error.4)
  (rt:do-test 'cl-test::mapcan.error.5)
  (rt:do-test 'cl-test::mapcan.error.6)
  (rt:do-test 'cl-test::mapcan.error.7)
  (rt:do-test 'cl-test::mapcan.error.8))
