(cl:in-package #:constrictor-test)

(defun test-mapcon ()
  (rt:do-test 'cl-test::mapcon.1)
  (rt:do-test 'cl-test::mapcon.2)
  (rt:do-test 'cl-test::mapcon.3)
  (rt:do-test 'cl-test::mapcon.4)
  (rt:do-test 'cl-test::mapcon.order.1)
  (rt:do-test 'cl-test::mapcon.error.1)
  (rt:do-test 'cl-test::mapcon.error.2)
  (rt:do-test 'cl-test::mapcon.error.3)
  (rt:do-test 'cl-test::mapcon.error.4)
  (rt:do-test 'cl-test::mapcon.error.5)
  (rt:do-test 'cl-test::mapcon.error.6)
  (rt:do-test 'cl-test::mapcon.error.7)
  (rt:do-test 'cl-test::mapcon.error.8))
