(cl:in-package #:constrictor-test)

(defun test-mapc ()
  (rt:do-test 'cl-test::mapc.1)
  (rt:do-test 'cl-test::mapc.2)
  (rt:do-test 'cl-test::mapc.3)
  (rt:do-test 'cl-test::mapc.4)
  (rt:do-test 'cl-test::mapc.5)
  (rt:do-test 'cl-test::mapc.6)
  (rt:do-test 'cl-test::mapc.order.1)
  (rt:do-test 'cl-test::mapc.error.1)
  (rt:do-test 'cl-test::mapc.error.2)
  (rt:do-test 'cl-test::mapc.error.3)
  (rt:do-test 'cl-test::mapc.error.4)
  (rt:do-test 'cl-test::mapc.error.5)
  (rt:do-test 'cl-test::mapc.error.6)
  (rt:do-test 'cl-test::mapc.error.7)
  (rt:do-test 'cl-test::mapc.error.8))
