(cl:in-package #:constrictor-test)

(defun test-maplist ()
  (rt:do-test 'cl-test::maplist.1)
  (rt:do-test 'cl-test::maplist.2)
  (rt:do-test 'cl-test::maplist.3)
  (rt:do-test 'cl-test::maplist.4)
  (rt:do-test 'cl-test::maplist.5)
  (rt:do-test 'cl-test::maplist.6)
  (rt:do-test 'cl-test::maplist.7)
  (rt:do-test 'cl-test::maplist.order.1)
  (rt:do-test 'cl-test::maplist.error.1)
  (rt:do-test 'cl-test::maplist.error.2)
  (rt:do-test 'cl-test::maplist.error.3)
  (rt:do-test 'cl-test::maplist.error.4)
  (rt:do-test 'cl-test::maplist.error.5)
  (rt:do-test 'cl-test::maplist.error.6)
  (rt:do-test 'cl-test::maplist.error.7)
  (rt:do-test 'cl-test::maplist.error.8)
  (rt:do-test 'cl-test::maplist.error.9)
  (rt:do-test 'cl-test::maplist.error.10)
  (rt:do-test 'cl-test::maplist.error.11))
