(cl:in-package #:constrictor-test)

(defun test-member-if ()
  (rt:do-test 'cl-test::member-if.1)
  (rt:do-test 'cl-test::member-if.2)
  (rt:do-test 'cl-test::member-if.3)
  (rt:do-test 'cl-test::member-if.4)
  (rt:do-test 'cl-test::member-if.5)
  (rt:do-test 'cl-test::member-if.order.1)
  (rt:do-test 'cl-test::member-if.order.2)
  (rt:do-test 'cl-test::member-if.keywords.1)
  (rt:do-test 'cl-test::member-if.allow-other-keys.2)
  (rt:do-test 'cl-test::member-if.allow-other-keys.3)
  (rt:do-test 'cl-test::member-if.allow-other-keys.4)
  (rt:do-test 'cl-test::member-if.allow-other-keys.5)
  (rt:do-test 'cl-test::member-if.allow-other-keys.6)
  (rt:do-test 'cl-test::member-if.allow-other-keys.7)
  (rt:do-test 'cl-test::member-if.error.1)
  (rt:do-test 'cl-test::member-if.error.2)
  (rt:do-test 'cl-test::member-if.error.3)
  (rt:do-test 'cl-test::member-if.error.4)
  (rt:do-test 'cl-test::member-if.error.5)
  (rt:do-test 'cl-test::member-if.error.6)
  (rt:do-test 'cl-test::member-if.error.7)
  (rt:do-test 'cl-test::member-if.error.8)
  (rt:do-test 'cl-test::member-if.error.9)
  (rt:do-test 'cl-test::member-if.error.10))
