(cl:in-package #:constrictor-test)

(defun test-nbutlast ()
  (rt:do-test 'cl-test::nbutlast.1)
  (rt:do-test 'cl-test::nbutlast.2)
  (rt:do-test 'cl-test::nbutlast.3)
  (rt:do-test 'cl-test::nbutlast.4)
  (rt:do-test 'cl-test::nbutlast.5)
  (rt:do-test 'cl-test::nbutlast.6)
  (rt:do-test 'cl-test::nbutlast.7)
  (rt:do-test 'cl-test::nbutlast.8)
  (rt:do-test 'cl-test::nbutlast.9)
  (rt:do-test 'cl-test::nbutlast.order.1)
  (rt:do-test 'cl-test::nbutlast.order.2)
  (rt:do-test 'cl-test::nbutlast.error.1)
  (rt:do-test 'cl-test::nbutlast.error.2)
  (rt:do-test 'cl-test::nbutlast.error.3)
  (rt:do-test 'cl-test::nbutlast.error.4)
  (rt:do-test 'cl-test::nbutlast.error.5)
  (rt:do-test 'cl-test::nbutlast.error.6)
  (rt:do-test 'cl-test::nbutlast.error.7)
  (rt:do-test 'cl-test::nbutlast.error.8)
  (rt:do-test 'cl-test::nbutlast.error.9)
  (rt:do-test 'cl-test::nbutlast.error.10))
