(cl:in-package #:constrictor-test)

(defun test-nsubst-if-not ()
  (rt:do-test 'cl-test::nsubst-if-not.1)
  (rt:do-test 'cl-test::nsubst-if-not.2)
  (rt:do-test 'cl-test::nsubst-if-not.3)
  (rt:do-test 'cl-test::nsubst-if-not.4)
  (rt:do-test 'cl-test::nsubst-if-not.5)
  (rt:do-test 'cl-test::nsubst-if-not.6)
  (rt:do-test 'cl-test::nsubst-if-not.7)
  (rt:do-test 'cl-test::nsubst-if-not.allow-other-keys.1)
  (rt:do-test 'cl-test::nsubst-if-not.allow-other-keys.2)
  (rt:do-test 'cl-test::nsubst-if-not.allow-other-keys.3)
  (rt:do-test 'cl-test::nsubst-if-not.allow-other-keys.4)
  (rt:do-test 'cl-test::nsubst-if-not.allow-other-keys.5)
  (rt:do-test 'cl-test::nsubst-if-not.keywords.6)
  (rt:do-test 'cl-test::nsubst-if-not.error.1)
  (rt:do-test 'cl-test::nsubst-if-not.error.2)
  (rt:do-test 'cl-test::nsubst-if-not.error.3)
  (rt:do-test 'cl-test::nsubst-if-not.error.4)
  (rt:do-test 'cl-test::nsubst-if-not.error.5)
  (rt:do-test 'cl-test::nsubst-if-not.error.6)
  (rt:do-test 'cl-test::nsubst-if-not.error.7)
  (rt:do-test 'cl-test::nsubst-if-not.error.8))
