(cl:in-package #:constrictor-test)

(defun test-pairlis ()
  (rt:do-test 'cl-test::pairlis.1)
  (rt:do-test 'cl-test::pairlis.2)
  (rt:do-test 'cl-test::pairlis.3)
  (rt:do-test 'cl-test::pairlis.4)
  (rt:do-test 'cl-test::pairlis.error.1)
  (rt:do-test 'cl-test::pairlis.error.2)
  (rt:do-test 'cl-test::pairlis.error.3)
  (rt:do-test 'cl-test::pairlis.error.4)
  (rt:do-test 'cl-test::pairlis.error.5)
  (rt:do-test 'cl-test::pairlis.error.6)
  (rt:do-test 'cl-test::pairlis.error.7)
  (rt:do-test 'cl-test::pairlis.error.8))
