(cl:in-package #:constrictor-test)

(defun test-rassoc-if ()
  (rt:do-test 'cl-test::rassoc-if.1)
  (rt:do-test 'cl-test::rassoc-if.2)
  (rt:do-test 'cl-test::rassoc-if.3)
  (rt:do-test 'cl-test::rassoc-if.4)
  (rt:do-test 'cl-test::rassoc-if.order.1)
  (rt:do-test 'cl-test::rassoc-if.order.2)
  (rt:do-test 'cl-test::rassoc-if.allow-other-keys.1)
  (rt:do-test 'cl-test::rassoc-if.allow-other-keys.2)
  (rt:do-test 'cl-test::rassoc-if.allow-other-keys.3)
  (rt:do-test 'cl-test::rassoc-if.allow-other-keys.4)
  (rt:do-test 'cl-test::rassoc-if.allow-other-keys.5)
  (rt:do-test 'cl-test::rassoc-if.keywords.6)
  (rt:do-test 'cl-test::rassoc-if.error.1)
  (rt:do-test 'cl-test::rassoc-if.error.2)
  (rt:do-test 'cl-test::rassoc-if.error.3)
  (rt:do-test 'cl-test::rassoc-if.error.4)
  (rt:do-test 'cl-test::rassoc-if.error.5)
  (rt:do-test 'cl-test::rassoc-if.error.6)
  (rt:do-test 'cl-test::rassoc-if.error.7)
  (rt:do-test 'cl-test::rassoc-if.error.8)
  (rt:do-test 'cl-test::rassoc-if.error.9)
  (rt:do-test 'cl-test::rassoc-if.error.10)
  (rt:do-test 'cl-test::rassoc-if.error.11)
  (rt:do-test 'cl-test::rassoc-if.error.12))
