(cl:in-package #:constrictor-test)

(defun test-subst-if ()
  (rt:do-test 'cl-test::subst-if.1)
  (rt:do-test 'cl-test::subst-if.2)
  (rt:do-test 'cl-test::subst-if.3)
  (rt:do-test 'cl-test::subst-if.4)
  (rt:do-test 'cl-test::subst-if.5)
  (rt:do-test 'cl-test::subst-if.6)
  (rt:do-test 'cl-test::subst-if.7)
  (rt:do-test 'cl-test::subst-if.allow-other-keys.1)
  (rt:do-test 'cl-test::subst-if.allow-other-keys.2)
  (rt:do-test 'cl-test::subst-if.allow-other-keys.3)
  (rt:do-test 'cl-test::subst-if.allow-other-keys.4)
  (rt:do-test 'cl-test::subst-if.allow-other-keys.5)
  (rt:do-test 'cl-test::subst-if.keywords.6)
  (rt:do-test 'cl-test::subst-if.error.1)
  (rt:do-test 'cl-test::subst-if.error.2)
  (rt:do-test 'cl-test::subst-if.error.3)
  (rt:do-test 'cl-test::subst-if.error.4)
  (rt:do-test 'cl-test::subst-if.error.5)
  (rt:do-test 'cl-test::subst-if.error.6)
  (rt:do-test 'cl-test::subst-if.error.7)
  (rt:do-test 'cl-test::subst-if.error.8))
