(cl:in-package #:constrictor-test)

(defun test ()
  (test-endp)
  (test-subst)
  (test-subst-if)
  (test-subst-if-not)
  (test-assoc)
  (test-last)
  (test-butlast)
  (test-mapcar)
  (test-mapc)
  (test-mapl)
  (test-mapcan)
  (test-maplist)
  (test-mapcon)
  (test-acons)
  (values))
